### ISSUE TITLE
CRANET TX DUMMY MOCK

### ISSUE THREAD

**Issue by azamiya** [tigerscave/eight-js-easy-apps#25]
## 下記のmock作成宜しく

<img width="932" alt="スクリーンショット 2023-07-04 11 40 05" src="https://github.com/tigerscave/eight-js-easy-apps/assets/7720795/17850215-2755-4902-988b-a7e4124db1a7">

**Comment by mre1ght** [comment]
レバーの長さをいじると、50-99までの2桁と100以降の3桁で、右に位置が移動してしまいます。

検証ツールで見ましたが、「設定がdisplay: inlineになっています。変更してください。」となっています。CSSのstyleでinlineにはしている箇所はないのですが、、、
